### ISSUE TITLE
Issue #1 - Feature List

### ISSUE THREAD

**Issue by keginzburg** [adedushi/sike#2]
# Feature List
- [X] Should have 7 Features.
  - [X] 3 of those are User Auth, Render, and Production README.
  - [X] The other 4 are from the [Feature List](https://github.com/appacademy/cohort-resources/blob/master/full_stack_projects/mvp_guidelines.md) or your PM will have clarified them with you.
- [X] Contains a description sentence of the app
- [X] Includes two to three detailed bullets on functionality and presentation of feature
- [X] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [X] Estimates how long it will take the code each Feature
- [X] Correctly formatted
  - [X] Features are listed in an ordered list
  - [X] Each Feature is broken down into bullet points

## Comments
This document looks great.

1. Only note is that Cart should be restricted to logged in users and reviews should only be allowed for users who have submitted those items to their cart previously.

**Comment by adedushi** [comment]
Do you prefer that I add those restrictions if Nike's website does not have them in place?

**Comment by keginzburg** [comment]
For our purposes yes. Making it so that users can add to the cart before logging in is a cart associated with browser cookies. We're more concerned with making Cart into a CRUD resource between our frontend and backend.

**Comment by adedushi** [comment]
Updated the feature list so only logged in users will be able to add items to cart
