### ISSUE TITLE
Issue #3 - Sample State

### ISSUE THREAD

**Issue by keginzburg** [adedushi/sike#4]
# Sample State
- [X] State shape is flat!
- [X] State's keys are camelCased
- [X] All keys within the values in the state are accessible in the schema
- [X] Correctly formatted
  - [X] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
  - [X] Top level slices
    - [X] `entities`
    - [X] `session`
    - [X] `errors` (here or in `ui`)
    - [X] `ui` (if needed)
  - [X] Should NOT have nested slices, aka `comments` inside of `posts`
   + Some info from other tables is ok, for instance:
    + the author username and imageurl for a post. basically any info that the user can't change
    + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
1. If we scale down our favorites and reviews, shouldn't both of these reference a `productId` instead of an `optionId`?
2. I believe your options need a `productId` foreign key as well, even in frontend state.

**Comment by adedushi** [comment]
1. Can make changes to cart and favorites slices after we discuss (post-auth)
2. Updated the options slice to include `productId`
