### ISSUE TITLE
Issue #4 - Backend Routes

### ISSUE THREAD

**Issue by keginzburg** [adedushi/sike#5]
# Backend Routes
- [X] Contains the following sections: HTML, API Endpoints(Backend)
- [X] Each route has a description
- [X] API Endpoint routes contains wildcard variables written in `snake_case`
- [ ] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [ ] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
  + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments
1. We should avoid our `PATCH /api/users/:id` route for now because user updating is not necessary for our User Auth feature. We could pursue this as a bonus later.
2. We should also avoid our `POST` and `PATCH /api/products/:id` route because customerts are unable to use Nike.com to create or update listed items.
3. Do we need any routes relating to cart?
4. Do we not need a `PATCH` and `DELETE` route for our reviews?

**Comment by adedushi** [comment]
1/2/3. Updated the backend routes to based on those comments.
4. It sounds strange, but Nike's website doesn't users to update or delete reviews so I may leave it as create-only.
